### ISSUE TITLE
Tokens from file: new file name pattern

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/python-tokens#13]
New token spec:

```yaml
apiVersion: "zalando.org/v1"
kind: PlatformCredentialsSet
metadata:
   name: my-app-credentials
spec:
   application: my-app
   tokens:
     full-access:
       privileges:
         - com.zalando::foobar.write
         - com.zalando::acme.full
     read-only:
       privileges:
         - com.zalando::foobar.read
 ```

becomes:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-app-credentials
type: Opaque
data:
  full-access-token-type: Bearer
  full-access-token-secret: JwAbc123.. # JWT token
  read-only-token-type: Bearer
  read-only-token-secret: JwBcd456.. # JWT token
```

Note the new "-token-secret" suffix.
